import cron from "node-cron";
import { storage } from "../storage";
import { twilioService } from "../services/twilio";
import { openaiService } from "../services/openai";

class FollowUpJob {
  private isRunning = false;

  start() {
    // Run every hour
    cron.schedule("0 * * * *", async () => {
      if (this.isRunning) {
        console.log("Follow-up job already running, skipping...");
        return;
      }

      this.isRunning = true;
      console.log("Starting follow-up job...");

      try {
        await this.processFollowUps();
        await this.scheduleNewFollowUps();
      } catch (error) {
        console.error("Follow-up job failed:", error);
      } finally {
        this.isRunning = false;
      }
    });

    console.log("Follow-up job scheduled to run every hour");
  }

  private async processFollowUps() {
    const pendingFollowUps = await storage.getPendingFollowUps();
    console.log(`Processing ${pendingFollowUps.length} pending follow-ups`);

    for (const followUp of pendingFollowUps) {
      try {
        if (followUp.type === "sms" && followUp.leadId) {
          const lead = await storage.getLead(followUp.leadId, adminUser?.id || 1);
          
          if (lead && lead.phone) {
            let message = followUp.message;
            
            // Generate personalized follow-up message if none exists
            if (!message) {
              message = await openaiService.generateFollowUpMessage(lead, lead.organizationId || null);
            }

            if (message) {
              await twilioService.sendSms(lead.phone, message);
              
              // Store the sent message
              await storage.createSmsMessage({
                leadId: lead.id,
                phone: lead.phone,
                direction: "outbound",
                content: message,
                status: "sent",
              });

              await storage.markFollowUpCompleted(followUp.id);
              console.log(`Follow-up sent to ${lead.phone}`);
            }
          }
        }
      } catch (error) {
        console.error(`Failed to process follow-up ${followUp.id}:`, error);
      }
    }
  }

  private async scheduleNewFollowUps() {
    // Get leads that need follow-up (new leads older than 2 hours without follow-up)
    // For now, use admin user (will be improved with organization support)
    const adminUser = await storage.getUserByEmail("test@cleanflow.com");
    if (!adminUser) return;
    
    const leads = await storage.getLeads(adminUser.id, "new");
    const twoHoursAgo = new Date(Date.now() - 2 * 60 * 60 * 1000);

    for (const lead of leads) {
      if (lead.createdAt && new Date(lead.createdAt) < twoHoursAgo) {
        // Check if this lead already has pending follow-ups
        const existingFollowUps = await storage.getPendingFollowUps();
        const hasExistingFollowUp = existingFollowUps.some(f => f.leadId === lead.id);

        if (!hasExistingFollowUp) {
          // Schedule follow-up for leads without response
          await storage.createFollowUp({
            leadId: lead.id,
            type: "sms",
            scheduledFor: new Date(Date.now() + 30 * 60 * 1000), // 30 minutes from now
            message: null, // Will be generated by AI
          });

          console.log(`Scheduled follow-up for lead ${lead.id}`);
        }
      }
    }
  }

  // Manual trigger for testing
  async triggerNow() {
    if (this.isRunning) {
      console.log("Follow-up job already running");
      return;
    }

    this.isRunning = true;
    try {
      await this.processFollowUps();
      await this.scheduleNewFollowUps();
      console.log("Manual follow-up job completed");
    } catch (error) {
      console.error("Manual follow-up job failed:", error);
    } finally {
      this.isRunning = false;
    }
  }
}

export const followUpJob = new FollowUpJob();

// Auto-start in production
if (process.env.NODE_ENV === "production") {
  followUpJob.start();
}
